# Generated by Django 5.0.6 on 2024-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMCModel',
            fields=[
                ('imc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imc_weight', models.FloatField()),
                ('imc_height', models.FloatField()),
                ('imc_result', models.FloatField()),
                ('imc_user_cpf', models.CharField(max_length=11)),
                ('imc_user_name', models.CharField(max_length=100)),
                ('imc_user_birthday', models.DateField()),
                ('imc_user_sex', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IMC',
                'verbose_name_plural': 'IMCs',
                'db_table': 'imc',
                'ordering': ['-created_at'],
            },
        ),
    ]
